### ISSUE TITLE
Miscolored icons in Plasma-Discover

### ISSUE THREAD

**Issue by ripefig** [cbrnix/Newaita#114]
![image](https://user-images.githubusercontent.com/45201036/63352697-41d5ef80-c36a-11e9-9156-f02c2d76c4d1.png)

I would recommend making the action icons black. The system Breeze monochrome icons adjust automatically according to background. I think this way, you will not need a separate dark theme and you will avoid poor contrast icons in mixed themes (for example Yaru or dark plasma/ light  app theme).

For example, this is Krunner with Newaita-light:
![image](https://user-images.githubusercontent.com/45201036/63353247-20c1ce80-c36b-11e9-9d14-c458338cdf83.png)

**Comment by demoy** [comment]
It's not quite automatic, the each monochrome icon has to styled in such a way that it inherit the active colorscheme. Which is easy enough.. until you realize how many icons have to changed.. Mixed themes overall are poorly supported in KDE not just in icons. And even when they inherit the colors monochrome icons choose the wrong colors in some areas like the window bar and the KDE settings.

**Comment by ripefig** [comment]
Can you clarify how that works @demoy? How do the other themes achieve this exactly?

BTW: example with Yaru Kvantum (same KDE color scheme)

Newaita:
![image](https://user-images.githubusercontent.com/45201036/63389627-044a8400-c3b5-11e9-8a76-6806cf6d32b1.png)

Papirus:
![image](https://user-images.githubusercontent.com/45201036/63389633-0876a180-c3b5-11e9-824e-3f08eae40957.png)

**Comment by demoy** [comment]
Here is an excerpt from document-open in la capitaine:
   <style type="text/css" id="current-color-scheme">
     .ColorScheme-Text {
       color:#4d4d4d;
     }
     </style>
 </defs>
   <path
      style="fill:currentColor;...unrelated stuff.."
    class="ColorScheme-Text"

Fill has to be set to currentColor, the class ColorScheme-Text sets the color for non-KDE applications. I choose La Capitaine because a year back I help to get this feature.. it was fun for the first 70+ icons but after seeing around a one hundred left I gave up and another KDE user finished them.
