### ISSUE TITLE
Consider using recolorable monochrochrome icons from DarK theme

### ISSUE THREAD

**Issue by ripefig** [cbrnix/Newaita#134]
This theme has a large collection of recolorable icons that could be used for symbolic and action icons. The biggest problem with Newaita right now is that the grayscale icons don't recolor based on the theme (so the light icons are invisible on a dark surface, e.g. a dark panel)

This theme also follows adwaita, so it should be pretty close to your style.

https://gitlab.com/sixsixfive/DarK-icons

**Comment by cbrnix** [comment]
None of the themes of the icons can be repainted on their own. There are clear shades for each background - light - for dark, dark - for light. Panel icons are changed by the PV.sh script. All other variations are a special case.

**Comment by ripefig** [comment]
Sorry for the misinformation. DarK does not, unfortunately support color schemes.

HOWEVER, Papirus and Breeze DEFINITELY do support variable color schemes. Proof:

This is with a light gtk/qt theme:
![image](https://user-images.githubusercontent.com/45201036/66252670-dbb0fa80-e766-11e9-84df-9d83d35c0363.png)

This is with dark gtk/qt theme:
![image](https://user-images.githubusercontent.com/45201036/66252682-f71c0580-e766-11e9-8065-11f8580c5c4f.png)

Both examples use the exact same `Paipus` icon theme, I only changed the gtk theme variant and the kde color scheme. I did not use `Papirus-dark` - I don't EVEN HAVE IT INSTALLED. Breeze can also do this - it recolors automatically - you can test it yourself.

Details here: https://github.com/cbrnix/Newaita/issues/114#issuecomment-523234056

**Comment by ripefig** [comment]
PS: You could create an issue with the DarK icons, asking the maintainer to support color schemes. Then, if he agrees to do it, you could just use his icon theme for symbolic and action icons. 

The icons could then also be used in the Adwaita++ icon theme https://github.com/Bonandry/adwaita-plus. So it could help improve three icon themes (Newaita, Adwaita++, and Dark).

**Comment by cbrnix** [comment]
own only gtk3 theme color symbolic icons!  they are in my topic and change in the same way.  Other themes can choose the icons themselves (this is indicated in the configuration).  It does not depend on the icons themselves.  Once again I say - none of the existing icon themes change the color of actions on their own.  Not a single one.  Because it is not feasible in principle at the software level

**Comment by cbrnix** [comment]
Now for the second sentence.  If you like a part of the icons of another theme, simply delete the corresponding directory and write down the icons you want to use in .theme.  I will not do this due to differences in license and status of a completely unique topic

**Comment by ripefig** [comment]
It is possible. Papirus, breeze and several others already do this. Try it for yourself. Just put papirus in your icons dir and change the gtk theme and/or KDE color scheme.

I refer you again to this [comment](https://github.com/cbrnix/Newaita/issues/114#issuecomment-523234056) as well as my own screenshot, both of which prove it's possible.

> I will not do this due to differences in license

Dark icon themes don't seem to have a licence. I think it's just Gnome monochrome icons mixed in with some original unlicensed work, so it's certainly not proprietary. But that's your decision obviously.

**Comment by cbrnix** [comment]
Just open index.theme for the theme you are using and you will see that the theme of the icons is written there (simple, dark or light). That’s all magic.

**Comment by ripefig** [comment]
It's not there and I should know, because I composed that index.theme myself! It doesn't define ANY icon theme, and - to repeat - I do NOT even have `Papirus-dark` installed.

Please, just read the comment I linked where @demoy explains how it's done in svg.

**Comment by cbrnix** [comment]
Yes, it is possible that at the level of svg itself it is likely to set such parameters. But in the near future, in any case, I will not be able to do this. The volume of work is too large (in addition to the need to constantly add new icons). I’ll postpone it indefinitely

**Comment by demoy** [comment]
@ripefig you can probably change the color to match your specific theme using sed something like:
find . -exec sed -i -e 's/e0e0e0/dbe7ff/g' {} ;

This command will replace the colors e0e0e0 [toolbar icons in Newaita dark] with dbe7ff (replace dbe7ff with your prefered color) "cd" to the icon directory in your terminal before running the lines (make a backup of the theme since this modifies the theme) .

You can read about sed here (http://www.grymoire.com/Unix/Sed.html)

You can use any color-picker (firefox has one in its options for example) to get the color of any icon you want to replace, and just substitute it in the "e0e0e0" for it above.

Now if you want the tiny folders to have a different color than the toolbar (for those "hybrid" themes ) run the same command again but this time only in "places" directory of the theme (this gets the folders). But change the color to replace "e0e0e0" in my example to whatever you change it to when you first ran the command,

Let me know if any of this is confusing to you or if the commands missed some icons.

Side-note rant: I have played with KDE theming enough to get the impression that these adaptive monochrome icons don't have that much to the impact to the presentation of the theme. They don't even match the text beside them well enough since the text is [usually] anti-alias and that affects the color of the text. So the text and icon are often shades off (which can be more visually displeasing to some than just being different colors). Cheerio.

**Comment by demoy** [comment]
> It is possible. Papirus, breeze and several others already do this. Try it for yourself. Just put papirus in your icons dir and change the gtk theme and/or KDE color scheme. The icons will change color without you doing anything.
> 
> I refer you again to this [comment](https://github.com/cbrnix/Newaita/issues/114#issuecomment-523234056) as well as my own screenshot, both of which prove it's possible.
> 
> > I will not do this due to differences in license
> 
> DarK icon theme doesn't seem to have a licence at all. I think it's just Gnome monochrome icons mixed in with some original unlicensed work, so it's certainly not proprietary. But that's your decision obviously.
> 
> edit: oops, it does have a licence. It's just like yours except it's CC 4 instead of CC 3

WARNING something not having a licenses DOES NOT MEAN its free. Peoples works are implicitly protected by intellectual property laws. Sorry for the caps but avoid unlicensed/non-public domain stuff because you can be sued whenever the owner feels like it, even 50 years later!

**Comment by ripefig** [comment]
I'm not interested in changing the icon colors. It should be possible to change the action icon en masse to make them compatible with color schemes. I'll probably look into it later, unless someone else beats me to it.

**Comment by demoy** [comment]
"Enmass and only action icons.." you can make a .sh file with execute permission and have the script cd to the action directory in the theme first before using sed. Python is also popular for scripts.

Here's a link on passing variable arguments [such as to specify colors and directories] to .sh:
 https://unix.stackexchange.com/questions/31414/how-can-i-pass-a-command-line-argument-into-a-shell-script

**Comment by ripefig** [comment]
@demoy this wouldn't fix the dark gtk applications that end up being broken by this icon theme. There is no substitute for having a single theme that is compatible with both light and dark themes.

Example:

![image](https://user-images.githubusercontent.com/45201036/67738236-d1f57c80-fa1e-11e9-9424-7a20111bfb01.png)
