### ISSUE TITLE
[ Discussion ] Change the actions icon to Suru++ actions

### ISSUE THREAD

**Issue by otavioschwanck** [cbrnix/Newaita#70]
Newaita:
![image](https://user-images.githubusercontent.com/9551316/53979971-ee3e5500-40ed-11e9-95e9-ea05f1c8f8c8.png)

Suru++:
![image](https://user-images.githubusercontent.com/9551316/53979992-f8f8ea00-40ed-11e9-8b88-1e24308f6ef4.png)

Also removed the window titlebar buttons, look too fancy.

**Comment by ripefig** [comment]
I'd like to see monochrome symbolics in general. They are needed because they can adapt to dark backgrounds easily. It's hard these days to have an environment where you don't have mixed light and dark backgrounds, and the current theme can't adapt to that.

Why not use [Gnome actions/status icons](https://gitlab.gnome.org/GNOME/adwaita-icon-theme) as the starting point instead? Gnome's designs are much more professional than anything else. You can always supplement them with  Suru or whatever. Plus, it makes sense to use Gnome stuff, given that this theme is supposed to be related to Adwaita.

**Comment by ripefig** [comment]
Actually maybe just change the existing actions and status icons to monochrome. You should be able to do this with a script.

**Comment by cbrnix** [comment]
Be patient for a while, please. After about a week, I’ll update where the new action symbolic will be, then I’ll change all action icons to monochrome and more expressive ones.

**Comment by ripefig** [comment]
I recommend using Gnome's new symbolic and action icons as much a possible for this. They are very well done.
